
# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.2"

[[override]]
  name="github.com/openshift/client-go"
  branch="release-3.11"

[[override]]
  name="github.com/openshift/api"
  branch="release-3.11"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.4"

[[override]]
  name = "github.com/kubernetes-incubator/service-catalog"
  version = "=v0.1.30"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false
  unused-packages = false

[[override]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=v0.1.1"

[[override]]
  name="github.com/sirupsen/logrus"
  version="v1.0.5"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"