apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: exports.component.k8s.io
spec:
  group: component.k8s.io
  version: v1alpha1
  names:
    kind: Export
    listKind: ExportList
    plural: exports
    singular: export
  scope: Namespaced
