apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: links.component.k8s.io
spec:
  group: component.k8s.io
  names:
    kind: Link
    listKind: LinkList
    plural: links
    singular: link
  scope: Namespaced
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
