apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: services.devexp.runtime.redhat.com
spec:
  group: devexp.runtime.redhat.com
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
    categories:
      - all
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
