apiVersion: v1
kind: ServiceAccount
metadata:
  name: component-operator
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: component-operator
rules:
  - apiGroups:
      - component.k8s.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: component-operator
subjects:
  - kind: ServiceAccount
    name: component-operator
roleRef:
  kind: Role
  name: component-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: component-operator
  template:
    metadata:
      labels:
        name: component-operator
    spec:
      serviceAccountName: component-operator
      containers:
        - name: component-operator
          image: quay.io/snowdrop/component-operator:master
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - component-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "component-operator"
