apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spring-boot-operator
  template:
    metadata:
      labels:
        name: spring-boot-operator
    spec:
      serviceAccountName: spring-boot-operator
      containers:
        - name: spring-boot-operator
          image: quay.io/snowdrop/spring-boot-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - spring-boot-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "spring-boot-operator"
