apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sb-operator
  template:
    metadata:
      labels:
        name: sb-operator
    spec:
      serviceAccountName: sb-operator
      containers:
        - name: sb-operator
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - sb-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "sb-operator"
