kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: component-operator
rules:
- apiGroups:
  - component.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
    - build.openshift.io
  resources:
    - builds
    - buildconfigs
  verbs:
    - "*"
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: component-operator
subjects:
- kind: ServiceAccount
  name: component-operator
roleRef:
  kind: Role
  name: component-operator
  apiGroup: rbac.authorization.k8s.io
