apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Full Lifecycle
    description: Developer Operator aiming to generate/install k8s resources of a microservice (aka component)
    categories: "Developer Tools"
    containerImage: quay.io/snowdrop/component-operator:master
    createdAt: 2019-03-07
    support: Charles Moulliard
    certified: "false"
  name: component-operator.v0.2.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Component
      name: components.component.k8s.io
      version: v1alpha1
  description: Placeholder description
  displayName: Component Operator
  install:
    spec:
      deployments:
      - name: component-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: component-operator
          strategy: {}
          template:
            metadata:
              creationTimestamp: null
              labels:
                name: component-operator
            spec:
              containers:
              - command:
                - component-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: component-operator
                image: quay.io/snowdrop/component-operator:master
                imagePullPolicy: Always
                name: component-operator
                ports:
                - containerPort: 60000
                  name: metrics
                resources: {}
              serviceAccountName: component-operator
      permissions:
      - rules:
        - apiGroups:
          - component.k8s.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        serviceAccountName: component-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider:
    name: Snowdrop Team
  version: 0.2.0
