apiVersion: appdev.snowdrop.me/v1alpha1
kind: Component
metadata:
  name: fruit-endpoint
spec:
  links:
  - name: Env Var to be injected
    targetComponentName: fruit-client
    kind: Env
    envs:
    - name: OPENSHIFT_ENDPOINT_FRUIT
      value: http://fruit-backend:8080/api/fruits