apiVersion: component.k8s.io/v1alpha1
kind: Component
metadata:
  name: my-spring-boot-link
spec:
  link:
    name: Secret to be injectd as EnvVar using Service's secret
    targetcomponentname: my-spring-boot
    kind: Secret
    ref: my-postgresql-db