apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  # See doc - https://github.com/operator-framework/operator-marketplace#installing-an-operator-using-marketplace concerning
  # installed-upstream-community-operators
  name: installed-upstream-community-operators
spec:
  targetNamespace: operators
  packages: component
  csDisplayName: "Component Operator"
  csPublisher: "Snowdrop"