apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: component-operator
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: ch007m
  displayName: "Component Operator"
  publisher: "Snowdrop"