apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  labels:
    tekton.dev/task: s2i-kaniko-push
  name: dummy-test-kaniko
spec:
  inputs:
    params:
    - name: moduleDirName
      value: fruit-client-sb
    resources:
    - name: git
      resourceRef: {}
      resourceSpec:
        params:
        - name: revision
          value: master
        - name: url
          value: https://github.com/snowdrop/component-operator-demo.git
        type: git
  outputs:
    resources:
    - name: image
      resourceRef: {}
      resourceSpec:
        params:
        - name: url
          value: docker-registry.default.svc:5000/test/dummy-test
        type: image
  serviceAccount: build-bot
  taskRef:
    kind: Task
    name: s2i-kaniko-push
