apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: s2i-buildah-push
spec:
  inputs:
    params:
      - default: quay.io/snowdrop/spring-boot-maven-s2i
        description: S2i base image
        name: baseImage
      - default: .
        description: The location of the path to run s2i from
        name: contextPath
      - default: .
        description: The name of the directory containing the project (maven, ...)
          to be compiled
        name: moduleDirName
      - default: "false"
        description: Verify registry certificates
        name: verifyTLS
      - default: /workspace/git
        description: Git path where project is cloned
        name: workspacePath
    resources:
      - name: git
        outputImageDir: ""
        targetPath: ""
        type: git
  outputs:
    resources:
      - name: image
        outputImageDir: /builder/image-outputs/image
        targetPath: ""
        type: image
  steps:
    - name: cat
      command:
        - bash
        - -c
        - echo $HOME;ls -la $HOME/.docker; ls $HOME/.docker/config.json
      image: quay.io/openshift-pipeline/tektoncd-pipeline-bash
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: libcontainers
    - name: generate
      args:
        - ${inputs.params.contextPath}
        - ${inputs.params.baseImage}
        - --as-dockerfile
        - /sources/Dockerfile.gen
        - --image-scripts-url
        - image:///usr/local/s2i
        - --env
        - MAVEN_ARGS_APPEND=-pl ${inputs.params.moduleDirName}
        - --env
        - MAVEN_S2I_ARTIFACT_DIRS=${inputs.params.moduleDirName}/target
        - --env
        - S2I_SOURCE_DEPLOYMENTS_FILTER=*.jar
      image: quay.io/openshift-pipeline/s2i-buildah
      resources: {}
      volumeMounts:
        - mountPath: /sources
          name: generatedsources
      workingDir: ${inputs.params.workspacePath}
    - name: build
      args:
        - bud
        - --tls-verify=${inputs.params.verifyTLS}
        - --layers
        - -f
        - /sources/Dockerfile.gen
        - -t
        - ${outputs.resources.image.url}
        - .
      command:
        - buildah
      image: quay.io/buildah/stable
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: libcontainers
        - mountPath: /sources
          name: generatedsources
      workingDir: /sources
    - name: push
      env:
      #- name: REGISTRY_AUTH_FILE
      #  value: /home/builder/docker/docker.json
      args:
        - push
        - --creds=build:eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0ZXN0MSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJidWlsZC10b2tlbi13MjJtayIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJidWlsZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijg4NDA2YmFlLWExNjItMTFlOS1iYmQ5LTEwN2I0NGIwMzU0MCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp0ZXN0MTpidWlsZCJ9.QWkfxsGtdik7troDVCisgK3mfYi0esKLhjBx4ikhYbIbDnLxXnZfdCXUO4dRHRJC7inDhs3724PdYlYWAsn4nuHHwvJcV07q9oo3adYYrZBn_FmRr_ZcW-90jeOCxYEF0Sa1-gp1CKkgUUOJU_MLpwW-lTybOnTiY039DJ51nJtVS4Z_xynEIjmNFQ_lDKedoEUte72UN8LlBfousm2j9fmI8jnsJJeab44c25mUt9jJTespzs2ACAgXzYE3LhVDayHRCSPntg5IS19k3i898n-PLdrABjEuMKeeg926Cu5ryO-SVUNGAR0xvazmH0Idl-REuP8w1C-kE9yp6mngrA
        - --tls-verify=${inputs.params.verifyTLS}
        - docker://${outputs.resources.image.url}
      command:
        - buildah
      #image: quay.io/buildah/stable
      image: quay.io/openshift-pipeline/buildah
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: libcontainers
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  volumes:
    - emptyDir: {}
      name: generatedsources
    - emptyDir: {}
      name: libcontainers
